#!/usr/bin/env bash

set -eux

[[ "$GITHUB_REF" != refs/tags/* ]] && echo "${GITHUB_REF} is not a tag, exiting..." && exit 78
VERSION=$(basename "$GITHUB_REF")

IFS="/" read -r org repo <<< "$GITHUB_REPOSITORY"

cd "$HOME"
go get -u github.com/digitalocean/github-changelog-generator
cd "$GITHUB_WORKSPACE"

tfile=$(mktemp "/tmp/$repo-CHANGELOG-XXXXXX")
echo "$VERSION" >"$tfile"
echo "" >>"$tfile"
github-changelog-generator -org "$org" -repo "$repo" >>"$tfile"

/usr/local/bin/hub release create --file "$tfile" "$VERSION"
