#!/usr/bin/env bash

set -eux

[[ "$GITHUB_REF" != refs/tags/* ]] && echo "${GITHUB_REF} is not a tag, exiting..." && exit 78
VERSION=$(basename "$GITHUB_REF")

IFS="/" read -r org repo <<< "$GITHUB_REPOSITORY"

go get -u github.com/digitalocean/github-changelog-generator

tfile=$(mktemp "/tmp/$repo-CHANGELOG-XXXXXX")
echo "$VERSION" >"$tfile"
echo "" >>"$tfile"
github-changelog-generator -org "$org" -repo "$repo" >>"$tfile"

cat "$tfile"

hub version

echo "$RELEASE_TOKEN"

GITHUB_TOKEN="$RELEASE_TOKEN" hub release create --file="$tfile" "$VERSION"
