name: CI

on: push

jobs:
  blahblah:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: release
      uses: ./.github/actions/github-release
      env:
        RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
